export declare const MILLIS = 1;
export declare const MILLISECOND = 1;
export declare const SEC: number;
export declare const SECOND: number;
export declare const MIN: number;
export declare const MINUTE: number;
export declare const HOUR: number;
export declare const DAY: number;
export declare const WEEK: number;
export declare const MONTH = 2628002880;
export declare const YEAR = 31536000000;
export declare const DECADE = 315360000000;
export declare const MIN_Z_INDEX = "-99999";
export declare const MAX_Z_INDEX = "99999";
export declare const ACTIVE_ELEMENT = "selectedElement";
export declare const DRAWING_CANVAS = "drawingCanvas";
export declare const DRAWING_CANVAS_MOUSE_COORDINATE = "mouseCoordinate";
export declare const DESIGN_ELEMENT_WRAPPER = "designElementWrapper";
export declare const CONTEXT_MENU = "contextMenu";
export declare const CLIPBOARD = "clipboard";
export declare const EVENT_DESELECT = "designElementDeselection";
export declare const EVENT_SELECT = "designElementSelection";
export declare const EVENT_DATA = "designElementEventData";
export declare const EXTENDED_TOOLS = "extendedTools";
export declare const APPCONTAINER = "appContainer";
export declare const EXTENSION_SCRIPT = "extensionScript";
export declare const BUILTIN_EXTENSION = "builtinExtension";
export declare const INSTALLED_EXTENSION = "installedExtension";
export declare const ENABLED_EXTENSION = "enabledExtension";
export declare const DISABLED_EXTENSION = "disabledExtension";
