import BaseComponent from './BaseComponent';
import IAppContainer from './model/IAppContainer';
declare class AppContainer extends BaseComponent implements IAppContainer {
    private menuBar;
    private toolBar;
    private actionBar;
    private horizontalRuler;
    private verticalRuler;
    private drawingToolBar;
    private drawingCanvas;
    private colorPalette;
    private verticalScrollBar;
    private horizontalScrollBar;
    private statusBar;
    private consolecanvas;
    private leftSideBar;
    private parserContainer;
    private tabPane;
    contextMenu: BaseComponent;
    constructor();
    getMenuBar(): BaseComponent;
    getToolBar(): BaseComponent;
    getActionBar(): BaseComponent;
    getHorizontalRuler(): BaseComponent;
    getVerticalRuler(): BaseComponent;
    getDrawingToolBar(): BaseComponent;
    getDrawingCanvas(): BaseComponent;
    getColorPalette(): BaseComponent;
    getVerticalScrollBar(): BaseComponent;
    getHorizontalScrollBar(): BaseComponent;
    getStatusBar(): BaseComponent;
    getConsoleCanvas(): BaseComponent;
    getLeftSideBar(): BaseComponent;
    getParserContainer(): BaseComponent;
    getTabPane(): BaseComponent;
    getContextMenu(): BaseComponent;
}
export default AppContainer;
