import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import ReactDOM from 'react-dom/client';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import NotFound from './common/NotFound';
import App from './App';
import { register } from './customElementRegistration';
import ExtensionManager from './extension/page/ExtensionManager';
register();
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(_jsx(BrowserRouter, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", Component: (props) => _jsx(App, Object.assign({}, props)) }), _jsx(Route, { path: "/extension", Component: (props) => _jsx(ExtensionManager, Object.assign({}, props)) }), _jsx(Route, { path: "*", Component: (props) => _jsx(NotFound, Object.assign({}, props)) })] }) }));
