export const MILLIS = 1;
export const MILLISECOND = 1;
export const SEC = MILLIS * 1000;
export const SECOND = MILLIS * 1000;
export const MIN = SECOND * 60;
export const MINUTE = SECOND * 60;
export const HOUR = MINUTE * 60;
export const DAY = HOUR * 24;
export const WEEK = DAY * 7;
export const MONTH = 2_628_002_880;
export const YEAR = 31_536_000_000;
export const DECADE = 315_360_000_000;

export const ACTIVE_ELEMENT = "selectedElement"
export const DRAWING_CANVAS = "drawingCanvas"
export const DESIGN_ELEMENT_WRAPPER = "designElementWrapper"
export const CONTEXT_MENU = "contextMenu"
export const CLIPBOARD = "clipboard"
export const EVENT_DESELECT = "designElementDeselection"
export const EVENT_SELECT = "designElementSelection"
export const EVENT_DATA = "designElementEventData"
export const EXTENDED_TOOLS = "extendedTools"
